### ISSUE TITLE
Prototype functionality

### ISSUE THREAD

**Issue by SusannaSansone** [ISA-tools/MAGEtoISAconverter#1]
Get the MAGEtab converter functional to support the majority of MAGEtab input.

**Comment by proccaserra** [comment]
Working MAGE-TAB converter. Also has the ability to work in Command line to fetch files from ArrayExpress given an accession number. Also works on local MAGE-TAB files and creates an ISAtab File. There are some problems when finding the correct technology to use for an assay. For instance, some MAGE-TAB files in the AE archive don&#39;t have the correct technology defined and this causes some problems (e.g. set as Sequencing assay, but it&#39;s a microarray assay or set as Chip-Chip when it&#39;s actually RNA-Seq). Closed by 8665f640824e08ce43a4fc1c8f0e48281f671ee0
