### ISSUE TITLE
Missing Assay Files

### ISSUE THREAD

**Issue by psm3426** [ISA-tools/MAGEtoISAconverter#16]
Hello,

I just tried out the new parser, and I've noticed that there are some studies that seem to be successfully converted (no error messages), but have missing assay files.  In the investigation file, there will be multiple assay files listed in the Study Assay section, but no corresponding files exist after conversion.

Some examples are E-MTAB-857, E-GEOD-15292, E-GEOD-28833, and E-ERAD-12.

I'm not really sure why this happens.

**Comment by eamonnmag** [comment]
This is most likely down to unrecognised assay types. The way of describing assays is inconsistent within mage-tab so we had to write a lot of checks in for the different types. Will look in to this.

**Comment by psm3426** [comment]
Thank you!

**Comment by proccaserra** [comment]
Hi Psalm,

I just checked E-GEOD-28833, and E-ERAD-12 and i have missed possible
values used by ArrayExpress (MBD-Seq) or inconsistent use (for instance
using "non-genomic" for library source and other for library strategy in
the former when RNA-Seq is used.

It is a similar situation for E-GEOD-15292
and E-MTAB-857 was not available tonight

I'll push the fix asap

thanks for reporting the issue and sorry for the inconvenience

Best

Philippe
