### ISSUE TITLE
SDRF File Not Found Error

### ISSUE THREAD

**Issue by psm3426** [ISA-tools/MAGEtoISAconverter#7]
Hello.  I've been using the JAR file on my local machine, and I noticed every so often when I converted files from ArrayExpress, that I would get an error that looked like this:

log4j:WARN No appenders could be found for logger (org.isatools.magetoisatab.io.DownloadUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
http://www.ebi.ac.uk/arrayexpress/files/E-GEOD-26565/E-GEOD-26565.idf.txt
Alternative Design Tag found at: Comment[AEExperimentType]      ChIP-seq       transcription profiling by array
transcription profiling
DNA microarray
transcription profiling
DNA microarray
http://www.ebi.ac.uk/arrayexpress/files/E-GEOD-26565/E-GEOD-26565.sdrf.txt
ERROR: file not found!

When looking at experiments that threw a similar error, it seems that the problem is that for these studies, the SDRF.TXT file is broken up into two files: xxx.HYB.SDRF.TXT and xxx.SEQ.SDRF.TXT.

It looks like line 56 of MAGETabObtain.java currently only allows the converter to find the SDRF file if there is a single file: sdrfUrl = "http://www.ebi.ac.uk/arrayexpress/files/" + accessionNumber + "/" + accessionNumber + ".sdrf.txt";

Could this be fixed please?

**Comment by SusannaSansone** [comment]
Current version 1.0 beta works with 'valid' MAGE-Tab where one SDRF exists; this beta version does not support a MAGE-Tab file where there are 2 SDRF files, as this case is NOT valid formatting according to the current MAGE-Tab specification.

**Comment by eamonnmag** [comment]
This is now fixed.
